package artisynth.models.rl.toymusclearm;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;

import artisynth.core.gui.ControlPanel;
import artisynth.core.materials.SimpleAxialMuscle;
import artisynth.core.mechmodels.AxialSpring;
import artisynth.core.mechmodels.ExcitationComponent;
import artisynth.core.mechmodels.FrameMarker;
import artisynth.core.mechmodels.HingeJoint;
import artisynth.core.mechmodels.MechModel;
import artisynth.core.mechmodels.MultiPointMuscle;
import artisynth.core.mechmodels.Muscle;
import artisynth.core.mechmodels.MuscleExciter;
import artisynth.core.mechmodels.RigidBody;
import artisynth.core.mechmodels.RigidCylinder;
import artisynth.core.mechmodels.Wrappable;
import artisynth.core.modelbase.ComponentList;
import artisynth.core.modelbase.ComponentState;
import artisynth.core.modelbase.StepAdjustment;
import artisynth.core.rl.FreeRunStrategy;
import artisynth.core.rl.Log;
import artisynth.core.rl.RlController;
import artisynth.core.rl.RlModelInterface;
import artisynth.core.rl.RlProp;
import artisynth.core.rl.RlTargetControllerInterface;
import artisynth.core.rl.StepStrategy;
import artisynth.core.rl.SteppedStrategy;
import artisynth.core.util.ArtisynthPath;
import artisynth.core.utils.Utils;
import artisynth.core.workspace.RootModel;
import maspack.geometry.MeshFactory;
import maspack.geometry.PolygonalMesh;
import maspack.matrix.Point3d;
import maspack.matrix.RigidTransform3d;
import maspack.matrix.Vector3d;
import maspack.render.RenderProps;

/**
 * RL-enabled adaptation of {@code artisynth.demos.tutorial.ToyMuscleArm}.
 *
 * <p>Two-link arm driven by four muscles (two axial, two wrapped); the agent
 * chooses muscle excitations to track a reference trajectory of joint angles
 * generated by a {@link JointAngleTrajectory}.
 *
 * <p>Joint angles {@code [theta0, theta1]} (rad) and angular velocities
 * (rad/s) are exposed through {@link #getRlProps()} as
 * {@code joint0}, {@code joint1}, {@code joint0_ref}, {@code joint1_ref}.
 *
 * <p>Episode duration and trajectory parameters are configurable via the
 * usual {@code -port}, {@code -episodeDuration}, {@code -amp0/-amp1} (deg),
 * {@code -freq0/-freq1} (Hz), {@code -phase0/-phase1} (deg) and
 * {@code -randomizeTraj} command-line flags.
 */
public class RlToyMuscleArmDemo extends RootModel implements RlModelInterface {

   protected int port = 8080;
   protected double episodeDuration = 10.0;   // seconds, advisory (Python truncates)
   protected double density = 1000.0;
   protected double stiffness = 1000.0;       // passive muscle stiffness
   protected boolean randomizeTraj = true;

   // Step strategy: how the simulation advances between agent actions.
   // Default = "stepped" (deterministic, fixed sub-step count per action).
   protected String stepStrategyName = "stepped";
   protected double waitAction = 0.05;        // sec, used only by stepped mode

   // Trajectory defaults (overridable from CLI). Amplitudes/phases in degrees;
   // converted to radians during build().
   protected double amp0Deg = 35.0;
   protected double amp1Deg = 60.0;
   protected double freq0Hz = 0.15;
   protected double freq1Hz = 0.20;
   protected double phase0Deg = 0.0;
   protected double phase1Deg = 90.0;

   protected MechModel myMech;
   protected HingeJoint myHinge0;
   protected HingeJoint myHinge1;
   protected RigidBody myLink0;
   protected RigidBody myLink1;

   protected ComponentList<MuscleExciter> mex =
      new ComponentList<MuscleExciter> (
         MuscleExciter.class, "mex", "muscleExcitation");

   protected RlController rlTrack;
   protected JointAngleTrajectory trajectory;
   protected TrajectoryTargetController targetMotionController;
   protected String trajKind = "multisine";   // "multisine" | "sin"

   private ComponentState initialState;
   private double myTime = 0.0;

   // ---------- Geometry helpers (verbatim port of ToyMuscleArm) ----------

   public Muscle addMuscle (
      RigidBody body0, double x0, double z0,
      RigidBody body1, double x1, double z1) {

      FrameMarker l0 = myMech.addFrameMarkerWorld (body0, new Point3d (x0, 0, z0));
      FrameMarker l1 = myMech.addFrameMarkerWorld (body1, new Point3d (x1, 0, z1));
      Muscle muscle = new Muscle();
      muscle.setMaterial (
         new SimpleAxialMuscle (stiffness, /*damping=*/0, /*fmax=*/1000));
      myMech.attachAxialSpring (l0, l1, muscle);
      return muscle;
   }

   public MultiPointMuscle addWrappedMuscle (
      RigidBody body0, double x0, double z0,
      RigidBody body1, double x1, double z1, Wrappable wrapBody) {

      FrameMarker l0 = myMech.addFrameMarkerWorld (body0, new Point3d (x0, 0, z0));
      FrameMarker l1 = myMech.addFrameMarkerWorld (body1, new Point3d (x1, 0, z1));
      MultiPointMuscle muscle = new MultiPointMuscle();
      muscle.setMaterial (
         new SimpleAxialMuscle (stiffness, /*damping=*/0, /*fmax=*/500));
      muscle.addPoint (l0);
      muscle.setSegmentWrappable (/*numknots=*/50);
      muscle.addPoint (l1);
      muscle.addWrappable (wrapBody);
      muscle.updateWrapSegments();
      myMech.addMultiPointSpring (muscle);
      return muscle;
   }

   public HingeJoint addHingeJoint (
      RigidBody body0, RigidBody body1,
      double x0, double z0, double minDeg, double maxDeg) {

      HingeJoint hinge = new HingeJoint (
         body0, body1, new Point3d (x0, 0, z0), new Vector3d (0, 1, 0));
      myMech.addBodyConnector (hinge);
      hinge.setThetaRange (minDeg, maxDeg);
      hinge.setShaftLength (0.4);
      RenderProps.setFaceColor (hinge, Color.BLUE);
      return hinge;
   }

   // ------------------------- Build -------------------------

   @Override
   public void build (String[] args) throws IOException {
      parseArgs (args);

      myMech = new MechModel ("mech");
      myMech.setInertialDamping (1.0);
      addModel (myMech);

      String geodir = ArtisynthPath.getSrcRelativePath (
         RlToyMuscleArmDemo.class, "data/");

      PolygonalMesh mesh = new PolygonalMesh (geodir + "bracketedBase.obj");
      RigidBody base = RigidBody.createFromMesh ("base", mesh, density, 1.0);
      base.setDynamic (false);
      myMech.addRigidBody (base);

      mesh = MeshFactory.createRoundedBox (0.6, 0.2, 0.2, /*nslices=*/20);
      myLink0 = RigidBody.createFromMesh ("link0", mesh, density, 1.0);
      myLink0.setPose (new RigidTransform3d (0, 0, 0.3));
      myMech.addRigidBody (myLink0);

      mesh = MeshFactory.createRoundedBox (0.6, 0.10, 0.15, /*nslices=*/20);
      myLink1 = RigidBody.createFromMesh ("link1", mesh, density, 1.0);
      myLink1.setPose (new RigidTransform3d (0, 0, 0.9));
      myMech.addRigidBody (myLink1);

      RigidCylinder cylinder = new RigidCylinder (
         "wrapSurface", /*rad=*/0.12, /*h=*/0.25, /*density=*/0, /*nsegs=*/32);
      cylinder.setPose (new RigidTransform3d (0, 0, 0.6, 0, 0, Math.PI / 2));
      myMech.addRigidBody (cylinder);
      myMech.attachFrame (cylinder, myLink1);

      myHinge0 = addHingeJoint (myLink0, base, 0, 0, -70, 70);
      myHinge1 = addHingeJoint (myLink1, myLink0, 0, 0.6, -120, 120);

      Muscle muscleL0 = addMuscle (myLink0, -0.1, 0.4, base, -0.48, -0.15);
      muscleL0.setName ("muscleL0");
      Muscle muscleR0 = addMuscle (myLink0,  0.1, 0.4, base,  0.48, -0.15);
      muscleR0.setName ("muscleR0");
      MultiPointMuscle muscleL1 = addWrappedMuscle (
         myLink1, -0.05, 1.2, myLink0, -0.1, 0.5, cylinder);
      muscleL1.setName ("muscleL1");
      MultiPointMuscle muscleR1 = addWrappedMuscle (
         myLink1,  0.05, 1.2, myLink0,  0.1, 0.5, cylinder);
      muscleR1.setName ("muscleR1");

      // Hold the model in a non-trivial pose so initial muscle lengths are
      // realistic, then anchor the rest lengths there.
      myHinge0.setTheta (-20);
      myHinge1.setTheta (38.4);
      myMech.updateWrapSegments();
      muscleL0.setRestLength (muscleL0.getLength());
      muscleR0.setRestLength (muscleR0.getLength());
      muscleL1.setRestLength (muscleL1.getLength());
      muscleR1.setRestLength (muscleR1.getLength());

      addExciter ("muscleL0e", muscleL0);
      addExciter ("muscleR0e", muscleR0);
      addExciter ("muscleL1e", muscleL1);
      addExciter ("muscleR1e", muscleR1);

      RenderProps.setSpindleLines (myMech, 0.02, Color.RED);
      RenderProps.setSphericalPoints (myMech, 0.02, Color.WHITE);
      RenderProps.setFaceColor (myMech, new Color (0.71f, 0.71f, 0.85f));
      RenderProps.setFaceColor (cylinder, new Color (0.75f, 0.61f, 0.75f));

      ControlPanel panel = new ControlPanel();
      panel.addWidget ("excitation L0", muscleL0, "excitation");
      panel.addWidget ("excitation R0", muscleR0, "excitation");
      panel.addWidget ("excitation L1", muscleL1, "excitation");
      panel.addWidget ("excitation R1", muscleR1, "excitation");
      addControlPanel (panel);

      addRlController();

      // Snapshot taken after full model construction (incl. controllers); used
      // by resetState() to restore a clean base for every episode.
      initialState = createState (null);
      getState (initialState);
   }

   private void addExciter (String name, ExcitationComponent target) {
      MuscleExciter m = new MuscleExciter (name);
      m.addTarget (target, 1.0);
      mex.add (m);
      myMech.addMuscleExciter (m);
   }

   // ------------------------- Sim time -------------------------

   @Override
   public StepAdjustment advance (double t0, double t1, int flags) {
      myTime = t0;
      return super.advance (t0, t1, flags);
   }

   // ---------------- RlModelInterface implementation ----------------

   @Override
   public void parseArgs (String[] args) {
      Map<String, String> dict = Utils.parseArgs (args);
      if (dict.containsKey ("-port"))
         port = Integer.parseInt (dict.get ("-port"));
      if (dict.containsKey ("-episodeDuration"))
         episodeDuration = Double.parseDouble (dict.get ("-episodeDuration"));
      if (dict.containsKey ("-amp0"))
         amp0Deg = Double.parseDouble (dict.get ("-amp0"));
      if (dict.containsKey ("-amp1"))
         amp1Deg = Double.parseDouble (dict.get ("-amp1"));
      if (dict.containsKey ("-freq0"))
         freq0Hz = Double.parseDouble (dict.get ("-freq0"));
      if (dict.containsKey ("-freq1"))
         freq1Hz = Double.parseDouble (dict.get ("-freq1"));
      if (dict.containsKey ("-phase0"))
         phase0Deg = Double.parseDouble (dict.get ("-phase0"));
      if (dict.containsKey ("-phase1"))
         phase1Deg = Double.parseDouble (dict.get ("-phase1"));
      if (dict.containsKey ("-randomizeTraj"))
         randomizeTraj = Boolean.parseBoolean (dict.get ("-randomizeTraj"));
      if (dict.containsKey ("-trajKind"))
         trajKind = dict.get ("-trajKind");
      if (dict.containsKey ("-stepStrategy"))
         stepStrategyName = dict.get ("-stepStrategy");
      if (dict.containsKey ("-waitAction"))
         waitAction = Double.parseDouble (dict.get ("-waitAction"));
   }

   /**
    * Build the reference {@link JointAngleTrajectory} based on the
    * {@code -trajKind} CLI argument. Custom shapes plug in by adding a new
    * case here and an implementation under
    * {@code artisynth.models.rl.toymusclearm}.
    */
   protected JointAngleTrajectory buildTrajectory() {
      switch (trajKind) {
         case "sin":
            return new SinCosTrajectory (
               Math.toRadians (amp0Deg), Math.toRadians (amp1Deg),
               freq0Hz, freq1Hz,
               Math.toRadians (phase0Deg), Math.toRadians (phase1Deg));
         case "multisine":
            return new MultiSineTrajectory();
         default:
            Log.info ("Unknown -trajKind '" + trajKind
                      + "'; falling back to 'multisine'.");
            return new MultiSineTrajectory();
      }
   }

   /**
    * Build a {@link StepStrategy} from the parsed CLI arguments. New
    * strategy types can be plugged in here without touching the controller.
    */
   protected StepStrategy buildStepStrategy() {
      switch (stepStrategyName) {
         case SteppedStrategy.NAME:
            return SteppedStrategy.fromDuration (waitAction, myMech.getMaxStepSize());
         case FreeRunStrategy.NAME:
            return new FreeRunStrategy();
         default:
            Log.info ("Unknown -stepStrategy '" + stepStrategyName
                      + "'; falling back to 'stepped'.");
            return SteppedStrategy.fromDuration (waitAction, myMech.getMaxStepSize());
      }
   }

   @Override
   public void addRlController() {
      trajectory = buildTrajectory();
      trajectory.setRandomizeEnabled (randomizeTraj);

      rlTrack = new RlController (myMech, this, "InvTracker", port);
      rlTrack.setStepStrategy (buildStepStrategy());
      for (MuscleExciter m : mex) {
         Log.debug ("Add exciter " + m.getName());
         rlTrack.addExciter (m);
      }

      targetMotionController =
         new TrajectoryTargetController (trajectory, rlTrack.random);

      addController (targetMotionController);
      addController (rlTrack);
      addControlPanel (rlTrack.getRlControlPanel());
      addControlPanel (rlTrack.getMuscleControlPanel());
   }

   @Override
   public void resetState() {
      setState (initialState);
      initialize (0.0);
      myTime = 0.0;
      targetMotionController.randomizeTarget();
   }

   @Override
   public ArrayList<RlProp> getRlProps() {
      double theta0 = myHinge0.getCoordinate (0);
      double theta1 = myHinge1.getCoordinate (0);
      double thetaDot0 = myHinge0.getCoordinateSpeed (0);
      double thetaDot1 = myHinge1.getCoordinateSpeed (0);

      double[] refAngles = targetMotionController.getCurrentAngles();
      double[] refVels = targetMotionController.getCurrentVelocities();

      ArrayList<RlProp> props = new ArrayList<RlProp> (4);
      props.add (rlProp ("joint0",     new double[] { theta0,    thetaDot0 }));
      props.add (rlProp ("joint1",     new double[] { theta1,    thetaDot1 }));
      props.add (rlProp ("joint0_ref", new double[] { refAngles[0], refVels[0] }));
      props.add (rlProp ("joint1_ref", new double[] { refAngles[1], refVels[1] }));
      return props;
   }

   private static RlProp rlProp (String name, double[] values) {
      RlProp p = new RlProp (name);
      p.setProp (values);
      return p;
   }

   @Override
   public RlTargetControllerInterface getTargetMotionController() {
      return targetMotionController;
   }

   @Override
   public double getTime() {
      return myTime;
   }

   public double getEpisodeDuration() {
      return episodeDuration;
   }
}
